services:
  krosoft-extensions.redis:  
    container_name: krosoft.redis
    image: redis:7.4.7-alpine3.21
    restart: on-failure

  krosoft-extensions.samples.dotnet9.api:
    image: ${DOCKER_REGISTRY-}krosoft-extensions.samples.dotnet9.api:${TAG_VERSION}
