services:
  krosoft-extensions.redis: 
    restart: unless-stopped
    command: redis-server --requirepass EI0hKU2OBfPHNPfd
    environment:
      - REDIS_PASSWORD=EI0hKU2OBfPHNPfd
    ports:
          - "6376:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "EI0hKU2OBfPHNPfd", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3      

  krosoft-extensions.samples.dotnet9.api:
    build:
      context: ..
      dockerfile: Krosoft.Extensions.Samples.DotNet9.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "6009:5000"
